# Sample .travis.yml for R projects
language: r

matrix:
  include:
    - os: linux
      dist: trusty
      r: devel
    - os: linux
      dist: trusty
      r: release      
    - os: osx
      r: release

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change
