# Sample .travis.yml for R projects
warnings_are_errors: false
language: r

matrix:
  include:
    - os: linux
      dist: trusty
      r: 
        - devel
        - release      
    - os: osx
      r: release
  allow_failures:
    - os: osx

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change
